### PR TITLE
Fixed #95 --alert-status failing to alert and allow absent value to alert on any status

### LINKED ISSUE #95: check-es-cluster-status.rb is broken
I'm not entirely sure of the intent behind the `--alert-status` flag however it's broken, it will never trigger an alert.

https://github.com/sensu-plugins/sensu-plugins-elasticsearch/blob/master/bin/check-es-cluster-status.rb#L148-L154 `options` need replacing with `config` and I imagine the  `!` needs removing and `==` needs replacing with `!=`.

I'm happy to create a PR if the above is correct.

### PR DESCRIPTION
**Pull request by rwky**
## Pull Request Checklist

Fixed #95

#### General

- [ x ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

Fixed #95

### CODE REVIEW

**Comment by majormoses** [comment]
@rwky can you please provide a testing artifact? A simple gist showing the command with it's IO works for me here.

**Comment by rwky** [comment]
Here you go https://gist.github.com/rwky/e5eabfa4ae1e7713c0503498cdc37dca

I only have a cluster with yellow status handy, the gist shows all the alert-status options

File: bin/check-es-cluster-status.rb [hunk 1]
```diff
@@ -145,13 +145,13 @@ def run
       when 'green'
         ok 'Cluster is green'
       when 'yellow'
-        if !options[:alert_status] == 'RED'
+        if ['YELLOW', ''].include? config[:alert_status]
```
Comment (majormoses) [inline bin/check-es-cluster-status.rb]: probably would just be better to do a `|| options[:alert_status].empty?` but because we do restrict the allowed inputs the risk of `include` is mitigated.

File: CHANGELOG.md [hunk 2]
```diff
@@ -5,6 +5,8 @@ This CHANGELOG follows the format listed at [Keep A Changelog](http://keepachang
 
 ## [Unreleased]
 
+- bin/check-es-cluster-health.rb and bin/check-es-cluster-status.rb fixed --alert-status failing to alert and allow absent value to alert on any status
```
Comment (majormoses) [inline CHANGELOG.md]: This should go under a `### Fixed` sub header per: https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-elasticsearch/versions/1.7.1

**Comment by driegel** [comment]
@rwky and @majormoses 
Thank you so much!
